#API Deployments
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-temperatura-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conversao-temperatura
  template:
    metadata:
      labels:
        app: conversao-temperatura
    spec:
      containers:
      - name: app
        image: douglasffilho/conversao-temperatura:latest
        resources:
          limits:
            memory: "256Mi"
            cpu: "1000m"
        ports:
        - containerPort: 8080

---

#API Service
apiVersion: v1
kind: Service
metadata:
  name: conversao-temperatura-service
spec:
  selector:
    app: conversao-temperatura
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
